import type { Metadata } from "next";
import { TopBar, Breadcrumb } from "@/app/createitem/components/TopBar";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const breadcrumbs: Breadcrumb[] = [
  { title: "MDMS", href: "/" },
  { title: "Create item", href: "/createitem" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Skip Links for Accessibility */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:top-0 focus:left-0 focus:bg-black focus:text-white focus:p-2 focus:rounded"
        >
          Skip to Content
        </a>

        <TopBar breadcrumbs={breadcrumbs} title="Create item" />
        {children}
      </body>
    </html>
  );
}
